account/urls.py
from django.urls import path
from . import views



app_name="account"

urlpatterns=[
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
    path('register',views.user_register,name='register'),
]

blog/urls.py
from django.urls import path
from . import views

app_name="blog"
urlpatterns=[
    path('detail/<slug:slug>', views.post_detail,name="article-detail"),
    path('list/',views.article_list,name="article_list"),
    path('search/',views.search,name="search")
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_app.urls')),
    path('',include('account.urls')),
    path('articles/',include('blog.urls'))
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from . import views

# urlpatterns=[
#     path('',views.home)
# ]

app_name='home_app'

urlpatterns=[
    path('',views.home,name='main')
]

account/models.py
from django.contrib.auth.models import User
from django.db import models

# class user(models.Model):
#     username=models.CharField(max_length=50)
#     email=models.CharField(max_length=50)
#     password1=models.CharField(max_length=50)
#     password2=models.CharField(max_length=50)
#
#     def __str__(self):
#         return self.username


class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    fathers_name=models.CharField(max_length=50)
    melicode=models.CharField(max_length=20)
    image=models.ImageField(upload_to='profiles/images',blank=True,null=True)

    def __str__(self):
        return self.user.username

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class category(models.Model):
    title=models.CharField(max_length=100)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
       return  self.title

class article(models.Model):
    CHOICE=(
        ('A','PYTHON'),
        ('B','DJANGO')
    )
    author=models.ForeignKey(User,on_delete=models.SET_DEFAULT,default='1')
    title=models.CharField(max_length=50,choices=CHOICE,unique_for_date='pub_date')
    category=models.ManyToManyField(category)
    body= models.TextField()
    image=models.ImageField(upload_to='images/articles')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    pub_date=models.DateField(default=timezone.now())
    myfile=models.FileField(upload_to='test',null=True)
    slug=models.SlugField(null=True,unique=True)

    class Meta:
        ordering=('-created',)


    def get_absolute_url(self):
        return reverse("blog:article-detail" , kwargs={'slug':self.slug})

    def __str__(self):
        return f"{self.title} - {self.body[:30]}"

class Comment(models.Model):
    article=models.ForeignKey(article,on_delete=models.CASCADE,related_name='comments')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='comments')
    parent=models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='replies')

    body=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return  self.body[:50]

account/views.py
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout


def user_login(request):
    if request.user.is_authenticated==True:
        return redirect('home_app:main')
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user =authenticate(request,username=username,password=password)
        if user is not None:
            login(request, user)
            return redirect('home_app:main')
    return render(request ,'account/login.html',context={})

def user_register(request):
    context={'eroors':[]}
    if request.user.is_authenticated==True:
        return  redirect('home_app:main')
    if request.method=="POST":
        username=request.POST.get('username')
        email=request.POST.get('email')
        password1=request.POST.get('password1')
        password2=request.POST.get('password2')
        if password1 != password2:
            context['eroors'].append('this tow password is not the same')
        return render(request,'account/register.html',context)

        user=User.objects.create(first_name=username,last_name=email,email=password1)
        login(request, user)
        return redirect('home_app:main')
    return render(request,'account/register.html',context={})


def user_logout(request):
    logout(request)
    return  redirect('home_app:main')

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import article
from django.core.paginator import Paginator


def post_detail(request,title):
    ads=get_object_or_404(article,slug=slug)
    return render(request, "blog/post-details.html",context={'article':ads})


def article_list(request):
    articles=article.objects.all()
    page_number=request.GET.get('page')
    paginator=Paginator(articles,1)
    object_list=paginator.get_page(page_number)
    return render(request ,'blog/article_list.html',context={'articles':object_list})

def search(request):
    q=request.GET.get('q')
    articles=article.objects.filter(title__contains=q)
    page_number=request.GET.get('page')
    paginator=Paginator(articles,1)
    object_list=paginator.get_page(page_number)
    return render(request,'blog/article_list.html', {"articles":object_list})

home_app/views.py
from django.shortcuts import render,redirect
from blog.models import article
from django.urls import reverse

def home(request):
    articles=article.objects.all()
    recent_articles=article.objects.all()[:3]
    return render(request,"home_app/index.html",context={'articles':articles,'recent_articles':recent_articles})

blog/templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>Our Recent Blog Entries</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>Stand Blog HTML5 Template</span>
                                <h4>Creative HTML Template For Bloggers!</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in articles %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>Lifestyle</span>
                                            <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ article.author }}</a></li>
                                                <li><a href="#">{{ article.created }}</a></li>
                                                <li><a href="#">12 Comments</a></li>
                                            </ul>
                                            <p>{{ article.body }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">Best Templates</a>,</li>
                                                            <li><a href="#">TemplateMo</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}



                            <div class="col-lg-12">
                                {% if articles.has_other_pages %}
                                    <ul class="page-numbers">
                                        {% if articles.has_previous %}
                                            <li><a href="?page={{ articles.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-angle-double-left"></i></a></li>
                                        {% endif %}

                                        {% for i in articles.paginator.page_range %}
                                            {% if articles.number == i %}

                                            <li class="active"><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% else %}
                                            <li ><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% endif %}


                                        {% endfor %}


                                        {% if articles.has_next %}
                                            <li><a href="?page={{ articles.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-angle-double-right"></i></a></li>

                                        {% endif %}

                                    </ul>

                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
                {% include "includes/sidebar.html" %}

            </div>
        </div>
    </section>


{% endblock %}

home_app/templates/home_app/index.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}

{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
      <div class="container-fluid">
        <div class="owl-banner owl-carousel">
          <div class="item">
            <img src="{% static 'images/banner-item-01.jpg' %}" alt="">
            <div class="item-content">
              <div class="main-content">
                <div class="meta-category">
                  <span>Fashion</span>
                </div>
                <a href="post-details.html"><h4>Morbi dapibus condimentum</h4></a>
                <ul class="post-info">
                  <li><a href="#">Admin</a></li>
                  <li><a href="#">May 12, 2020</a></li>
                  <li><a href="#">12 Comments</a></li>
                </ul>
              </div>
            </div>
          </div>
            {% for article in articles %}
                <div class="item">
            <img src="{{ article.image.url }}" alt="{{ article.title }}">
            <div class="item-content">
              <div class="main-content">
                <div class="meta-category">
                  <span>{{ article.category.last.title }}</span>
                </div>
                <a href="#"><h4>{{ article.title }}</h4></a>
                <ul class="post-info">
                  <li><a href="#">{{ article.author.username }}</a></li>
                  <li><a href="#">{{ article.created }}</a></li>
                  <li><a href="#">24 Comments</a></li>
                </ul>
              </div>
            </div>
          </div>
            {% endfor %}

        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>Stand Blog HTML5 Template</span>
                  <h4>Creative HTML Template For Bloggers!</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">

                  {% for article in articles %}
                      <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{ article.image.url }}" alt="">
                    </div>
                    <div class="down-content">
                      <span>Lifestyle</span>
                      <a href=""><h4>{{ article.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.author.username }}</a></li>
                        <li><a href="#">{{ article.created }}</a></li>
                        <li><a href="#">12 Comments</a></li>
                      </ul>
                      <p>
                      {{ article.body }}
                      </p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Beauty</a>,</li>
                              <li><a href="#">Nature</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li>{% post_to_whatsapp article.get_absolute_url "whatsappp" %}</li>

                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                  {% endfor %}


                <div class="col-lg-12">
                  <div class="main-button">
                    <a href="{% url 'blog:article_list' %}">View All Posts</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% include "includes/sidebar.html" %}
        </div>
      </div>
    </section>

{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
 <body>
  <head>

{% include "includes/head_refrences.html" %}
  </head>

   {% include "includes/header.html" %}

  {% block content %}
  {% endblock %}

{% include "includes/footer.html" %}

{% include "includes/footer_refrences.html" %}


  </body>
</html>

templates/includes/footer.html
{% load static %}

<footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Behance</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Dribbble</a></li>
            </ul>
          </div>
          <div class="col-lg-12">
            <div class="copyright-text">
              <p>Copyright 2020 Stand Blog Co.

                 | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer_refrences.html
{% load static %}


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'js/owl.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/accordions.js' %}"></script>

    <script language = "text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

templates/includes/head_refrences.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="TemplateMo">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet">

<title>Stand CSS Blog by TemplateMo</title>

<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.css' %}">

templates/includes/header.html
{% load static %}

 <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="index.html">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "blog:article_list" %}">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="post-details.html">Post Details</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact Us</a>
              </li>
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <div class="d-flex">
                         {% if request.user.first_name %}
                             {% if user.profile.image %}
                                 <img src="{{ user.profile.image.url }}" width="40px" height="40px" style="border: 2px solid black ; border-radius:100%" alt="">
                             {% else %}
                                 <img src="{% static 'images\blog-thumb-04.jpg' %}" width="40px" height="40px" style="border: 2px solid black ; border-radius:100%" alt="">
                             {% endif %}
                              <a class="nav-link" href="">{{ user.profile.fathers_name }}</a>
                             {% else %}
                             <a class="nav-link" href="">{{ request.user.username}}</a>
                             {% endif %}
                        <a   href="{% url 'account:logout' %}" class="mt-2 "><span class="bg bg-warning">logout</span></a>
                        </div>

                    {% else %}
                        <div class="d-flex">
                        <a class="nav-link" href="{% url 'account:login' %}">login</a>
                         <a class="nav-link" href="{% url 'account:register' %}">/register</a>

                        </div>


                    {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

templates/includes/sidebar.html
{% load static %}
<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            <div class="col-lg-12">
                <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="{% url "blog:search" %}">
                        <input type="text" name="q" class="searchText" placeholder="type to search..."
                               autocomplete="on">
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                        <ul>

                            {% for article in recent_article  %}

                            <li><a href="post-details.html">
                                <h5>{{ article.title }}</h5>
                                <span>{{ article.created }}</span>
                            </a></li>

                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                        <h2>Categories</h2>
                    </div>
                    <div class="content">
                        <ul>
                            <li><a href="#">- Nature Lifestyle</a></li>
                            <li><a href="#">- Awesome Layouts</a></li>
                            <li><a href="#">- Creative Ideas</a></li>
                            <li><a href="#">- Responsive Templates</a></li>
                            <li><a href="#">- HTML5 / CSS3 Templates</a></li>
                            <li><a href="#">- Creative &amp; Unique</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                        <h2>Tag Clouds</h2>
                    </div>
                    <div class="content">
                        <ul>
                            <li><a href="#">Lifestyle</a></li>
                            <li><a href="#">Creative</a></li>
                            <li><a href="#">HTML5</a></li>
                            <li><a href="#">Inspiration</a></li>
                            <li><a href="#">Motivation</a></li>
                            <li><a href="#">PSD</a></li>
                            <li><a href="#">Responsive</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>